# Generated by Django 6.1.1 on 2026-09-28 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва дисципліни')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ПІБ викладача')),
                ('department', models.CharField(blank=True, default='ІПЗ / КН', max_length=100, verbose_name='Кафедра')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(choices=[(1, '1-й тиждень (Чисельник)'), (2, '2-й тиждень (Знаменник)')], default=1, verbose_name='Тиждень')),
                ('day', models.CharField(choices=[('Monday', 'Понеділок'), ('Tuesday', 'Вівторок'), ('Wednesday', 'Середа'), ('Thursday', 'Четвер'), ('Friday', "П'ятниця")], max_length=20, verbose_name='День тижня')),
                ('period', models.PositiveSmallIntegerField(verbose_name='Номер пари')),
                ('group_name', models.CharField(default='314-і', max_length=50, verbose_name='Група')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.subject', verbose_name='Дисципліна')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.teacher', verbose_name='Викладач')),
            ],
            options={
                'unique_together': {('week', 'day', 'period', 'teacher')},
            },
        ),
    ]
