# Generated by Django 6.1.1 on 2026-09-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='week',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 тиждень'), (2, '2 тиждень')], default=1, verbose_name='Тиждень'),
        ),
    ]
