# Generated by Django 6.1.1 on 2026-09-28 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_scheduleitem_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер аудиторії')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Місткість')),
            ],
        ),
        migrations.CreateModel(
            name='LessonRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(choices=[(1, '1 тиждень'), (2, '2 тиждень')], default=1, verbose_name='Тиждень')),
                ('group_name', models.CharField(default='314-і', max_length=50, verbose_name='Група')),
                ('hours_per_week', models.PositiveSmallIntegerField(default=1, verbose_name='Кількість пар на тиждень')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.teacher')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='scheduleitem',
            unique_together={('week', 'day', 'period', 'teacher')},
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.room', verbose_name='Аудиторія'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleitem',
            unique_together={('week', 'day', 'period', 'group_name'), ('week', 'day', 'period', 'room'), ('week', 'day', 'period', 'teacher')},
        ),
    ]
