# Generated by Django 6.1.1 on 2026-09-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_room_lessonrequirement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleitem',
            unique_together={('week', 'day', 'period', 'room'), ('week', 'day', 'period', 'teacher')},
        ),
        migrations.RemoveField(
            model_name='lessonrequirement',
            name='group_name',
        ),
        migrations.AddField(
            model_name='lessonrequirement',
            name='groups',
            field=models.CharField(default='314-і', help_text='Напр.: 314-і, 315-і', max_length=150, verbose_name='Групи через кому'),
        ),
        migrations.AddField(
            model_name='lessonrequirement',
            name='is_stream',
            field=models.BooleanField(default=False, verbose_name='Потокова лекція'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='groups',
            field=models.CharField(default='314-і', max_length=150, verbose_name='Групи'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='is_stream',
            field=models.BooleanField(default=False, verbose_name='Потокова лекція'),
        ),
        migrations.AlterField(
            model_name='lessonrequirement',
            name='hours_per_week',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кількість пар'),
        ),
        migrations.CreateModel(
            name='TeacherUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Понеділок'), ('Tuesday', 'Вівторок'), ('Wednesday', 'Середа'), ('Thursday', 'Четвер'), ('Friday', "П'ятниця")], max_length=20, verbose_name='День')),
                ('period', models.PositiveSmallIntegerField(default=0, verbose_name='Пара (0 = увесь день)')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='scheduler.teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='group_name',
        ),
    ]
